# Generated by Django 3.0.2 on 2020-02-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_pub',
            field=models.ImageField(blank=True, upload_to='posts/image/'),
        ),
    ]
