# Generated by Django 3.0.2 on 2020-02-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200216_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_pub',
            field=models.ImageField(blank=True, upload_to='posts/image/'),
        ),
    ]
