# Generated by Django 3.0.2 on 2020-02-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200218_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_pub',
            field=models.ImageField(blank=True, upload_to='posts/image/<built-in function id>/'),
        ),
    ]
