# Generated by Django 3.0.2 on 2020-01-14 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ivent', '0003_iventuserprofile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iventuserprofile',
            options={'verbose_name': 'Прогресс пользователей', 'verbose_name_plural': 'Прогресс пользователей'},
        ),
        migrations.AlterField(
            model_name='iventuserprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
