# Generated by Django 3.0.2 on 2020-01-14 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ivent', '0007_auto_20200114_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iventuserprofile',
            name='mass',
        ),
        migrations.AddField(
            model_name='iventuserprofile',
            name='DateCheck',
            field=models.DateField(auto_now=True, verbose_name='Дата фиксации'),
        ),
        migrations.CreateModel(
            name='IventUserProfile_photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='PhotoUsers')),
                ('IventUserProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ivent.IventUserProfile')),
            ],
        ),
    ]
