# Generated by Django 3.0.2 on 2020-01-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivent', '0008_auto_20200114_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iventuserprofile_photo',
            name='image',
            field=models.ImageField(upload_to='media/PhotoUsers'),
        ),
    ]
