# Generated by Django 3.0.2 on 2020-01-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivent', '0010_auto_20200114_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iventuserprofile_photo',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
