# Generated by Django 3.0.2 on 2020-01-22 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivent', '0011_auto_20200120_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iventuserprofile_photo',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
