# Generated by Django 3.0.2 on 2020-01-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivent', '0012_auto_20200122_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iventuserprofile_photo',
            name='image',
            field=models.ImageField(upload_to='media/PhotoUsers'),
        ),
    ]
