# Generated by Django 3.0.2 on 2020-01-22 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivent', '0013_auto_20200122_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iventuserprofile_photo',
            name='image',
            field=models.ImageField(upload_to='PhotoUsers'),
        ),
    ]
