# Generated by Django 3.0.2 on 2020-01-22 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivent', '0015_auto_20200122_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iventuserprofile_photo',
            name='image',
            field=models.ImageField(upload_to='PhotoUsers/', verbose_name='Изображение'),
        ),
    ]
