# Generated by Django 3.0.2 on 2020-01-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivent', '0019_auto_20200122_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ivent',
            name='url',
        ),
        migrations.RemoveField(
            model_name='iventuserprofile',
            name='url',
        ),
        migrations.AlterField(
            model_name='iventuserprofile_photo',
            name='image',
            field=models.ImageField(upload_to='PhotoUsers', verbose_name='Изображение'),
        ),
    ]
