# Generated by Django 3.0.2 on 2020-01-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivent', '0020_auto_20200130_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='ivent',
            name='image_logo',
            field=models.ImageField(default='', upload_to='IventLogo', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
