# Generated by Django 3.0.2 on 2020-01-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivent', '0022_auto_20200130_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivent',
            name='IventUserProfils',
            field=models.ManyToManyField(blank=True, to='ivent.IventUserProfile', verbose_name='Профиль участника'),
        ),
    ]
