# Generated by Django 3.0.2 on 2020-01-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivent', '0025_remove_iventuserprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='iventuserprofile',
            name='name',
            field=models.CharField(default='', max_length=150, verbose_name='Прогресс пользователей'),
            preserve_default=False,
        ),
    ]
