# Generated by Django 3.0.2 on 2020-02-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivent', '0026_iventuserprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivent',
            name='image_logo',
            field=models.ImageField(blank=True, upload_to='IventLogo', verbose_name='Изображение комнаты'),
        ),
    ]
