# Generated by Django 3.0.2 on 2020-02-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivent', '0027_auto_20200201_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivent',
            name='image_logo',
            field=models.ImageField(default='IventLogo/def.png', upload_to='IventLogo', verbose_name='Изображение комнаты'),
        ),
    ]
