# Generated by Django 3.0.2 on 2020-02-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivent', '0029_auto_20200201_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivent',
            name='image_logo',
            field=models.ImageField(blank=True, default='/IventLogo/def.png', upload_to='IventLogo', verbose_name='Изображение комнаты'),
        ),
    ]
