# Generated by Django 3.0.2 on 2020-02-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivent', '0036_auto_20200201_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='nk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Соревнование')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
    ]
