# Generated by Django 3.0.2 on 2020-02-05 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ivent', '0037_nk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nk',
        ),
    ]
